sudo: required
services:
  - docker
language: go
go: 1.16
env:
  global:
  - CGO_ENABLED = 0
  - GO111MODULE=on
  jobs:
  - SERVICE = eventservice
  - SERVICE = bookservice
install: true
script: 
  - pwd
  - cd $SERVICE
  - pwd
  - go build

